In [1]:
import numpy as np

In [ ]:
# 1. Write a NumPy program to test whether none of the elements of a given array is zero.
# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

arr = np.array([10, 20, 30, 5, 0, 0, 5])
size = arr.size
NonZerosCount = np.count_nonzero(arr)

number_of_zeros = size - NonZerosCount
if number_of_zeros != 0:
  print(f"there are {number_of_zeros} zeros in array")
else:
  print(f"Zero Not found in array")

there are 2 zeros in array


In [ ]:
# another solution
flag = np.any(arr == 0)
if flag:
  print("there are zeros in the array")
else:
  print("Zero not found")

there are zeros in the array


In [ ]:
# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

x = np.array([10, 20, 30, 40, 50, 60, 70])
y = np.array([10, 20, 30, 40, 50, 60, 60])

np.equal(x, y)

array([ True,  True,  True,  True,  True,  True, False])

In [ ]:
# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
x = np.ones(10)
y = np.zeros(10)
z = np.full(10, 5)

v = np.block([x, y, z])
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# 5. Write a NumPy program to create an array of the integers from 30 to70.
arr = np.arange(30, 71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [ ]:
# 6. Write a NumPy program to create a 3x3 identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 7. Write a NumPy program to generate a random number between 0 and 1

randomNumber = np.random.rand()
randomNumber

0.08293033012173678

In [ ]:
# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
np.random.randn(15)

array([ 1.31509518,  0.65039685, -0.34361676,  0.68482132, -0.34803681,
       -0.76116638, -1.20348631, -0.20971444, -0.90446535,  2.51105359,
       -0.02227718,  0.03461619,  0.52184862,  0.39231721,  1.50409904])

In [ ]:
# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
arr = np.arange(15, 56)[1:-1]
arr

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [ ]:
# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
arr = np.zeros((10, 10))
arr[0] = 1
arr[-1] = 1
for row in arr:
  row[0] = 1
  row[-1] = 1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
arr = np.diag(np.full(5, [1, 2, 3, 4, 5]))
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [2]:
#Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

matrix = np.ones((4, 4))
np.fill_diagonal(matrix, 0)
print(matrix)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


In [3]:
#Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

Mat1 = np.ones((3, 4))
Mat2 = np.zeros((5, 3))

np.savez('file.npz', Ones_Mat=Mat1, Zeros_Mat=Mat2)

with np.load('file.npz') as file:
    Mat1 = file['Ones_Mat']
    Mat2 = file['Zeros_Mat']
    print(Mat1)
    print(Mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select
np.random.seed(42)
array = np.random.rand(40)
print(array)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249]
